CCOL-393. Add feature for group-specific rate limits
wishabi/bullmq pull request #5
Opened 2020-08-26 20:19 UTC by csingh

2020-08-26 20:53 UTC, dorner requested changes
This looks awesome - is there some documentation you need to update?

2020-08-26 20:54 UTC, csingh commented
@dorner you're too quick! Yup i was meaning to update the PR, I added some description, but plan to add similar stuff somewhere in the documentation after I try to clear up the wording.

2020-08-27 15:59 UTC, csingh commented
@dorner @sarrangan I added some docs!

2020-08-27 16:17 UTC, sarrangan commented
Looks pretty elegant! Also like the cute examples in the README 👍  LGTM ✅

2020-08-27 18:04 UTC, dorner commented
So looking back at this I'm a little confused as to how this will solve the item scraper problem. Wouldn't we need to set up this config in advance for every merchant? I thought we'd be able to have a key inside the payload (e.g. a groupRateKey) that could define the number?

2020-08-27 18:25 UTC, csingh commented
@dorner we decided that we're going to ignore the need to change these on the fly until it becomes a pain. For now, yes we'll just set them up in advance for any retailers that don't follow the default.

In the future though, I was thinking one possible solution is to just create a Bullwhip API that can read/write the configs to Redis. Should be pretty simple, and then whatever UI that will control this can hook into that.

2020-09-01 19:16 UTC, merged